package net.certifi.audittablegen;

/**
 * Audit Table Gen
 * This is just a shell app generated by NetBeans as a Maven Java project
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "This does not do anything yet." );
    }
}
